### ISSUE TITLE
Bug: Spider & TB API 요청을 하지 못함

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-webtool#32]
재현:
```
# git clone https://github.com/jihoon-seo/cb-deployer.git
# cd cb-deployer
# docker-compose up
```

---

브라우저에서 http://cb-webtool:1234/Driver/list 들어가면
다음과 같이 로그가 찍힙니다.

```docker-compose
cb-webtool      | [00] {"time":"2020-03-27T02:41:01.694664501Z","id":"","remote_ip":"192.168.0.101","host":"192.168.0.102:1234","method":"GET","uri":"/Driver/list","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","status":200,"error":"","latency":281707,"latency_human":"281.707µs","bytes_in":0,"bytes_out":16557}
cb-webtool      | [00] {"time":"2020-03-27T02:41:01.780550418Z","id":"","remote_ip":"192.168.0.101","host":"192.168.0.102:1234","method":"GET","uri":"/ns","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","status":404,"error":"code=404, message=Not Found","latency":13503,"latency_human":"13.503µs","bytes_in":0,"bytes_out":24}
cb-webtool      | [00] {"time":"2020-03-27T02:41:01.784143757Z","id":"","remote_ip":"192.168.0.101","host":"192.168.0.102:1234","method":"GET","uri":"/driver","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","status":404,"error":"code=404, message=Not Found","latency":16154,"latency_human":"16.154µs","bytes_in":0,"bytes_out":24}
```

- `192.168.0.101`: 브라우저가 돌아가는 Windows PC 입니다.
- `192.168.0.102`: Ubuntu VM 이고, Spider, TB, Webtool, API-GW 를 docker-compose 로 띄웠습니다.

1. 첫번째 줄: 브라우저에서 -> Webtool 에게 `GET /Driver/list` 했습니다. 성공적입니다.
2. 두번째 줄: 브라우저에서 -> Webtool 에게 `GET /ns` 했습니다. Webtool 에는 `/ns` API 가 없으므로 404 떴습니다.
3. 세번째 줄: 브라우저에서 -> Webtool 에게 `GET /driver` 했습니다. Webtool 에는 `/driver` API 가 없으므로 404 떴습니다.

* `docker-compose.yaml` 에서
```yaml
    environment:
      - API_GW=http://cb-restapigw:8000
      - SPIDER_URL=http://cb-restapigw:8000/spider
      - TUMBLE_URL=http://cb-restapigw:8000/tumblebug
```
이렇게도 해 보고
```yaml
    environment:
      - API_GW=http://cb-restapigw:8000
      - SPIDER_URL=http://cb-spider:1024/spider
      - TUMBLE_URL=http://cb-tumblebug:1323/tumblebug
```
이렇게도 해 봤는데, 동일합니다.

---

[제안]
https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/CloudConnectionHandler.go#L11
변수명을 `CloudConnectionUrl` -> `SpiderUrl` 로 하시면 가독성이 더 좋을 것 같습니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/CloudConnectionHandler.go#L24
`url := SPIDER_URL + "/driver/" + drivername` 이 되어야 할 것으로 보입니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/CloudConnectionHandler.go#L56
`url := SPIDER_URL + "/driver"` 이 되어야 할 것으로 보입니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/CloudConnectionHandler.go#L71
`url := SPIDER_URL + "/driver"` 이 되어야 할 것으로 보입니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/CloudConnectionHandler.go#L86
`url := SPIDER_URL + "/driver"` 이 되어야 할 것으로 보입니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/McisHandler.go#L14
변수명을 `MCISUrl` -> `TumblebugUrl` 로 하시면 가독성이 더 좋을 것 같습니다.

https://github.com/cloud-barista/cb-webtool/blob/9146b6a603f2b10b8307ba15283482accc07517e/src/service/NameSpaceHandler.go#L13
변수명을 `NameSpaceUrl` -> `TumblebugUrl` 로 하시면 가독성이 더 좋을 것 같습니다.

**Comment by jazmandorf** [comment]
처리 완료
