### ISSUE TITLE
What should I do when getting 'No response was received from the cb-tumblebug server.'?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-webtool#72]
cb-webtool을 설치하여 실행한 후 "Login Success"까지는 확인하였습니다.
잠시 뒤 아래와 같은 메시지가 알림창으로 나타나는데 콘솔에는 관련한 로그를 확인할 수 없습니다.
혹시 로그를 어디서 확인할 수 있을까요?
```
No response was received from the cb-tumblebug server.
Check the cb-tumblebug server
Call Url : http://129.xxx.yyy.zzz:1323/tumblebug/ns
```

아래와 같이 cb-tumblebug는 정상 동작하는 것으로 확인하였고, 로그인시 cb-tumblebug에는 접근 로그가 나타나지 않았습니다.
```
➜  cb-webtool git:(master) ✗ curl http://129.xxx.yyy.zzz:1323
Hello, World! This is cloud-barista cb-tumblebug%                         
```

**Comment by dev4unet** [comment]
위 에러의 경우 로그인 이후 NS 정보를 받아오기 위해 웹 브라우저에서 텀블벅에 정보를 요청했으나
텀블벅으로부터 장시간 아무런 응답도 받지 못해서 PC에서 텀블벅에 정상적으로 접근 가능한지 확인하라는 안내 메시지입니다.
**서버가 아닌 웹도구 테스트에 사용한 PC에서 텀블벅의 http://129.xxx.yyy.zzz:1323/ 주소에 정상적으로 접근 가능한지 확인이 필요할 것같습니다.**

참고로, 웹도구에서 연동프레임 워크의 REST 호출은 자바스크립트에서 진행되기 때문에 모두 클라이언트의 브라우저에서 호출됩니다.
따라서, 세부 로그를 보고 싶으시면 사용하는 웹 브라우저의 개발 도구를 이용하시면됩니다.
크롬이나 IE의 경우 F12를 눌러서 Debug 창을 띄울 수 있으며 Console이나 Network 탭을 통해서 확인하시기 바랍니다.

사용하는 PC에서 http://129.xxx.yyy.zzz:1323/ 주소로 접근하는데 문제가 없는데도 에러가 계속 발생하나면 브라우저의 Console 로그를 부탁드리겠습니다.

**Comment by sykim-etri** [comment]
사용하는 PC에서 http://129.xxx.yyy.zzz:1323/ 주소로 접근되지 않는 것을 확인하였고 방화벽 이슈임을 확인하였습니다.
답변 감사합니다.
